In [1]:
import tensorflow as tf
import numpy as np

In [5]:
print tf.concat((tf.ones_like(y[:1])*2, y[:-1]), -1)

Tensor("concat_1:0", shape=(3,), dtype=int32)


In [17]:
graph = tf.Graph()

In [25]:
x = tf.constant(np.random.rand(10, 10))
y = tf.constant(np.random.rand(10, 10))
con = tf.ones_like(y[:, :1])*2
pt = tf.Print(con, [con])

In [26]:
with tf.Session as sess:
    sess.run(pt)

AttributeError: __exit__

In [29]:
import tensorflow as tf
import numpy as np
x=tf.constant([2,3,4,5])
x=tf.Print(x,[x,x.shape,'any thing i want'],message='Debug message:',summarize=100)
with tf.Session() as sess:
    sess.run(x)

In [31]:
import tensorflow as tf

#define a variable to hold normal random values 
normal_rv = tf.Variable(tf.truncated_normal([2,3],stddev = 0.1))

#initialize the variable
init_op = tf.initialize_all_variables()

#run the graph
with tf.Session() as sess:
    sess.run(init_op) #execute init_op
    #print the random values that we sample
    print (sess.run(normal_rv))

[[-0.03293496 -0.0747735  -0.15191157]
 [-0.12567225 -0.00170633 -0.02800868]]


In [32]:
x = np.random.rand(32, 10)
y = np.random.rand(32, 10)

In [33]:
x, y

(array([[0.42274018, 0.51208521, 0.99826579, 0.98895944, 0.39056036,
         0.92950552, 0.64846932, 0.01170796, 0.12306798, 0.47472371],
        [0.41045019, 0.38767891, 0.14576349, 0.22770481, 0.82291831,
         0.17708179, 0.35401406, 0.50397801, 0.96923315, 0.46027747],
        [0.72885808, 0.6387236 , 0.77828812, 0.71717797, 0.41730933,
         0.24555397, 0.68847064, 0.8758696 , 0.21680881, 0.16606599],
        [0.51539288, 0.34728793, 0.31526842, 0.73639915, 0.91120589,
         0.44055155, 0.78255915, 0.939394  , 0.72877666, 0.42780264],
        [0.71894708, 0.49493498, 0.28855637, 0.88771364, 0.06407763,
         0.12271969, 0.1152135 , 0.27825149, 0.17163299, 0.16443649],
        [0.75547113, 0.73321818, 0.33769987, 0.6346342 , 0.39764333,
         0.14600481, 0.24296592, 0.90533492, 0.0558614 , 0.91842455],
        [0.8711683 , 0.45928969, 0.07083932, 0.46796171, 0.75795074,
         0.59011944, 0.48432669, 0.59140927, 0.92831966, 0.40293108],
        [0.69030239, 0.3417

In [36]:
tx = tf.convert_to_tensor(x, dtype = tf.float32)
ty = tf.convert_to_tensor(y, dtype = tf.float32)

In [38]:
tf.concat((tf.ones_like(ty[:, :1])*2, ty[:, :-1]), -1)

<tf.Tensor 'concat_2:0' shape=(32, 10) dtype=float32>

In [43]:
import tensorflow as tf
x = np.random.rand(2, 3)
y = np.random.rand(2, 3)
tx = tf.convert_to_tensor(x, dtype = tf.float32)
ty = tf.convert_to_tensor(y, dtype = tf.float32)
z = tf.concat((tf.ones_like(ty[:, :1])*2, ty[:, :-1]), -1)
with tf.Session():
  # We can also use 'c.eval()' here.
  print(tx.eval())
  print(ty.eval())
  print(z.eval())


[[0.97008127 0.36857504 0.47959355]
 [0.78774625 0.38952425 0.45700267]]
[[0.9747541  0.4108185  0.24075139]
 [0.88295287 0.11206398 0.08581316]]
[[2.         0.9747541  0.4108185 ]
 [2.         0.88295287 0.11206398]]


In [45]:
def batch_iter(data, batch_size, num_epochs, shuffle=True):
    """
    Generates a batch iterator for a dataset.
    """
    data = np.asarray(data)
    print(data)
    print(data.shape)
    data_size = len(data)
    num_batches_per_epoch = int(len(data)/batch_size) + 1 
    for epoch in range(num_epochs):
        # Shuffle the data at each epoch
        if shuffle:
            shuffle_indices = np.random.permutation(np.arange(data_size))
            shuffled_data = data[shuffle_indices]
        else:
            shuffled_data = data
        for batch_num in range(num_batches_per_epoch):
            start_index = batch_num * batch_size
            end_index = min((batch_num + 1) * batch_size, data_size)
            yield shuffled_data[start_index:end_index]


In [46]:
batches = batch_iter([[0,1,1], [3,2,1], [3,2,4], [4,3,2], [6,1,2]], 2, 3)

In [47]:
batches

<generator object batch_iter at 0x7f0fa3d93f00>

In [49]:
batch = batches.next()
batch

[[0 1 1]
 [3 2 1]
 [3 2 4]
 [4 3 2]
 [6 1 2]]
(5, 3)


array([[3, 2, 4],
       [4, 3, 2]])

In [50]:
zip(*batch)

[(3, 4), (2, 3), (4, 2)]

In [112]:
h1 = tf.placeholder(tf.float32, shape=(None, 3, 4))
h2 = tf.placeholder(tf.float32, shape=(None, 3, 4))
h_q = tf.placeholder(tf.float32, shape=(None, 3, 4))
h_a = tf.placeholder(tf.float32, shape=(None, 3, 4))
h_q_mix = tf.concat([h1, h_q], -1)
h_a_mix = tf.concat([h2, h_a], -1)
reshape_a_t = tf.transpose(h_a_mix, [0, 2, 1])
S_qa_raw = tf.matmul(h_q_mix, reshape_a_t)
# reshape_S_qa = tf.reshape(S_qa_raw, [-1, 9])
# reshape_S_qa = tf.nn.softmax(reshape_S_qa)
# S_qa = tf.reshape(reshape_S_qa, [-1, 3, 3])
S_qa = tf.nn.softmax(S_qa_raw, dim=2)
S_aq = tf.transpose(S_qa, [0, 2, 1])
h_a_sum = tf.matmul(S_aq, h_q_mix)
h_q_sum = tf.matmul(S_qa, h_a_mix)
h_q_coa = tf.matmul(S_qa, h_a_sum)
h_a_coa = tf.matmul(S_aq, h_q_sum)
h_q_final = tf.concat([h_q_mix, h_a_sum, h_q_coa], -1)[:, -1, :]
h_a_final = tf.concat([h_a_mix, h_q_sum, h_a_coa], -1)[:, -1, :]

In [113]:
with tf.Session() as sess:
    np.random.seed(10)
    rand_array = np.random.rand(2, 3, 4)
    print(sess.run(h_q_final, feed_dict={h1: rand_array, h2: rand_array, h_q: rand_array, h_a: rand_array}))  # Will succeed.

[[0.16911083 0.08833981 0.68535984 0.95339334 0.16911083 0.08833981
  0.68535984 0.95339334 0.4606228  0.11753263 0.5636066  0.8978509
  0.4606228  0.11753263 0.5636066  0.8978509  0.5027802  0.11632372
  0.54418004 0.87489355 0.5027802  0.11632372 0.54418004 0.87489355]
 [0.54254436 0.14217004 0.37334076 0.6741336  0.54254436 0.14217004
  0.37334076 0.6741336  0.25902593 0.16034055 0.3661592  0.38297173
  0.25902593 0.16034055 0.3661592  0.38297173 0.5216734  0.36345404
  0.8283159  0.78806686 0.5216734  0.36345404 0.8283159  0.78806686]]
